### ISSUE TITLE
Sessions Ending early

### ISSUE THREAD

**Issue by Musa-Azeem** [smithandrewk/delta#50]
There may or may not be a bug where sessions are ending earlier than 10 minutes. Investigate

**Comment by Musa-Azeem** [comment]
oops. its supposed to 8 minutes (length of timer is 480000 ms, which is 8 minutes)

**Comment by smithandrewk** [comment]
Can we make it 30 minutes @Musa-Azeem

**Comment by Musa-Azeem** [comment]
Yes sir
